### ISSUE TITLE
Update bild_scraping.py

### ISSUE THREAD

**Issue by danvardan15** [BCCN-Prog/webscraping_2018#12]
This should be the format: (any other format hinders DB migration)
For more info check: [https://github.com/BCCN-Prog/webscraping_2018/commit/ef2d52378bd0a3e636c57df4722bc95b428c6ca7](url)

and:
*DailyPeriodPrediction:
- website (url) [MANDATORY]
- date_for_which_weather_is_predicted (timestamp in the form YYYYMMDDHH) [MANDATORY]
- city ('Berlin', 'Hamburg', etc.) [MANDATORY]
- time_for_which_weather_is_predicted (timestamp in the form YYYYMMDDHH) [MANDATORY]
- temperature (celsius) [MANDATORY]
- wind_speed (km/h)
- precipation_per (%)
- precipation_l (L/m^2)
- wind_direction ('N', 'W' etc.)
- condition ('clear', 'foggy', 'sunny')

**Comment by mavischer** [comment]
i won't be there tomorrow because i got a light infection, but i'll fix the issue from home

**Comment by mavischer** [comment]
i pushed it to the WS-0003, but couldn't push to WS-0007:  "Updates were rejected because a pushed branch tip is behind its remote counterpart. Check out this branch and integrate the remote changes". I lost track of what the branches mean and whether the version of bild_scraping on WS-0007 is behind or ahead of the one from WS-0003, so i didn't push to WS-0007. Let's talk about it next week. 
Two things I noticed about the format template:
There is a typo "precipation" instead of "precipitation". I named the variables the wrong way now to fit the standards and allow for db migration, but it might be nice to fix this globally if we have a minute. 
For the daily period prediction, don't we want to save the date when the prediction was made? (i.e. the current day or the day before)
For the daily period prediction, date_for_which... and time_for_which... are duplicates right now, would be nice to remove one and rename the other datetime_for_which...
